Add first increment
mkarulina/url-reduction-service pull request #1
Opened 2022-02-11 15:25 UTC by mkarulina

2022-02-18 15:46 UTC, mkarulina commented on cmd/shortener/main_test.go
> +			},
Текущий тест тест на редирект у меня проходит, но в тестах, которые запускаются на pr - ошибка в таком же сценарии. Предположительно из-за того, что при добавления заголовка location происходит редирект и в итоге мы получаем другой ответ. Пока не смогла разобраться, что нужно сделать, чтобы `autotests / shortenertest` прошел :(

2022-02-20 13:24 UTC, ASPecherkin requested changes

2022-02-20 13:24 UTC, ASPecherkin commented on cmd/shortener/main.go
> +var UrlsDB []SavedURL
Вопросы об этом коде

Первое:
почему не использовать map[string]string?  
Что мотивировало использовать массив с типом? 

Второе:
Лучше не использовать глобальные переменные, а передавать явно такие вещи в main в сам handler
То есть 
```go
type Hander struct {
store: SavedUrl
}

func (h *Handler) Handle(w http.ResponseWriter, r *http.Request) {
// logic
}
```

2022-02-20 13:24 UTC, ASPecherkin commented on cmd/shortener/shortener.go
> +		UrlsDB = append(UrlsDB, SavedURL{buf.String(), link})
Эта операция не конкурентно безопасна 
То есть - если у нас придёт несколько одновременных запросов на добавление - мы не можем гарантировать целостность данных 

Для этого проще всего будет добавить мьютекс к типу, в котором будем хранить данные 
простой пример можно посмотреть тут - https://gobyexample.com/mutexes

2022-02-22 19:22 UTC, mkarulina commented on cmd/shortener/main.go
> +var UrlsDB []SavedURL
1. Согласна, причин нет, поправила
2. Спасибо! Надеюсь, переписала правильно. Добавила мьютекс и передачу переменных

2022-02-22 20:23 UTC, ASPecherkin approved these changes
С тестом можем разобраться позднее, в остальном мне нравится как написано

2022-02-22 21:13 UTC, merged