2 sprint
mkarulina/url-reduction-service pull request #4
Opened 2022-04-11 14:55 UTC by mkarulina

2022-04-11 16:04 UTC, mkarulina commented
Есть проблемы с 8 инкрементом - не проходит тест и не могу обнаружить, что именно я описала неверно. Буду очень благодарна за помощь)

2022-04-12 19:44 UTC, lugingf requested changes
Ну у нас явно не отрабатывает POST корректно

> 2022/04/11 14:56:40 "POST http://localhost:8080/ HTTP/1.1" from 127.0.0.1:37114 - 400 62B in 18.4µs

2022-04-12 19:44 UTC, lugingf commented on cmd/shortener/main.go
> +func gzipHandler(handler http.Handler) http.Handler {
А почему gzip у нас отдельным хэндлером, а не middleware?

2022-04-12 19:49 UTC, lugingf commented on cmd/shortener/main.go
> +		} else if strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
Я бы предложил что-то вроде
```
		if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
			next.ServeHTTP(w, r)
			return
		}
```

2022-04-12 19:51 UTC, lugingf commented on internal/handlers/post_link_handler.go
> +	validURL := govalidator.IsURL(reqValue)
Вот тут корректно отрабатывает?

2022-04-14 22:21 UTC, mkarulina commented on internal/handlers/post_link_handler.go
> +	validURL := govalidator.IsURL(reqValue)
Спасибо! Почему-то до меня очень долго доходило, что логику ридера нужно выносить в хэндлер - поправила, тест прошел)

2022-04-16 11:13 UTC, lugingf approved these changes
Принято)

2022-04-17 18:25 UTC, merged