Add 9-13 increment
mkarulina/url-reduction-service pull request #5
Opened 2022-05-07 17:56 UTC by mkarulina

2022-05-13 08:45 UTC, lugingf requested changes
Привет еще раз. Давай чуть переделаем работу. Ты домашку отправила - в дедлайн формально успела. Я ее заворачивать не буду, чтобы попытки не тратить, а ревью напишу тут
Давай соберем хэндлеры в один пакет.
Сделаем структуру Handler, методы которой уже будут тем самыми хэндлерами, которые будут обрабатывать запрос. Так будет проще работать со всякими ресурсами, базой например
Сделаем еще одну мидлвару - Auth, в которой:
  Будем проверять наличие куки юзера
  Если куки нет - генерим, подписываем устанавливаем
  Если кука есть - декодируем
Еще gzip тоже в мидлвару выносим. Потому что вот это все закомменчивание/раскомменчивание в куче файлов - не дело
Я проверил твой кодинг-декодинг - вроде работает. Есть подозрение, что где-то немного перенакручено по структуре.

2022-05-16 09:42 UTC, lugingf approved these changes
Принято!

2022-05-16 09:42 UTC, lugingf commented on internal/handlers/batch_links.go
> +		} else {
Этот else тут не нужен, тк у нас continue выше

2022-05-16 09:42 UTC, lugingf commented on internal/handlers/post_link.go
> +	} else {
и тут не нужен else)

2022-05-16 18:55 UTC, mkarulina commented on internal/handlers/post_link.go
> +	} else {
спасибо, для следующего пр поправила

2022-05-16 18:56 UTC, merged